### ISSUE TITLE
Unet是怎么计算光流的？

### ISSUE THREAD

**Issue by small-White-JJ** [HopLee6/RRIN#10]
感谢您的工作！我刚刚接触这个领域，很好奇RRIN中的Unet是如何计算光流的？

**Comment by HopLee6** [comment]
UNet以相邻的两帧图像作为输入，以无监督的方式输出正向光流和反向光流。每个光流图是通道为2的map，每个位置的二维向量表示光流矢量。生成的光流图用于后面的视频插值，使用真实的中间图像作为监督训练整个网络。综上，网络训练前UNet不具备计算光流的能力，网络训练后在插值任务的监督下可以生成光流。

**Comment by small-White-JJ** [comment]
> UNet以相邻的两帧图像作为输入，以无监督的方式输出正向光流和反向光流。每个光流图是通道为2的map，每个位置的二维向量表示光流矢量。生成的光流图用于后面的视频插值，使用真实的中间图像作为监督训练整个网络。综上，网络训练前UNet不具备计算光流的能力，网络训练后在插值任务的监督下可以生成光流。

感谢您的解答！
