### ISSUE TITLE
Code to train model

### ISSUE THREAD

**Issue by v-shmyhlo-ring** [HopLee6/RRIN#2]
Hey, thank you for your great work.

Do you plan to release code to train model? I am trying to reproduce your results using code from this repo and my training code but it doesn't seem to work.

**Comment by HopLee6** [comment]
I'm sorry, but I do not plan to release the training code.
However, the training procedure is elaborated in the paper. Be careful with **step size** and you may get the similar results.

**Comment by v-shmyhlo-ring** [comment]
@HopLee6 Understood, thank you!

**Comment by Srikarthikeyan4006** [comment]
> @HopLee6 Understood, thank you!

can you explain how to train .. i am new to this field
