### ISSUE TITLE
Cannot load pretrained model successfully.

### ISSUE THREAD

**Issue by xiaozhi2015** [HopLee6/RRIN#4]
@HopLee6 
Here is the error message:
![image](https://user-images.githubusercontent.com/12682406/81766915-b6107e80-9509-11ea-9406-1ca15cca7c71.png)

**Comment by HopLee6** [comment]
Bug fixed. 
Please try again.

**Comment by xiaozhi2015** [comment]
Much thx.  @HopLee6
