### ISSUE TITLE
RuntimeError with Middlebury dataset

### ISSUE THREAD

**Issue by rastaman7** [HopLee6/RRIN#5]
I tried using this code for Middlebury dataset. 
http://vision.middlebury.edu/flow/data/

For most sequences(Beanbags, DogDance, Grove2, Grove3, MiniCooper, Urban2  Urban3, Walking), it worked fine, but for some(Dimetrodon, Hydrangea, RubberWhale, Venus), I got a Runtime error.

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 380 and 368 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83

How can I fix this error?

**Comment by HopLee6** [comment]
Bug fixed. Try it again please.

**Comment by rastaman7** [comment]
If I added 
import numpy as np
it worked perfectly.
Thank you!
