### ISSUE TITLE
can not download the pretrained model ，can you check it

### ISSUE THREAD

**Issue by hiredd** [HopLee6/RRIN#6]
thanks very much~

**Comment by HopLee6** [comment]
I have checked the download link and it can be reached.
You may have to try proxy for onedrive.
If you still have trouble with it, I can email the pretrained model to you.

**Comment by hiredd** [comment]
> I have checked the download link and it can be reached.
> You may have to try proxy for onedrive.
> If you still have trouble with it, I can email the pretrained model to you.
for some reasons,  i can't download the  model  ,would you  kindly send me  the model(email: lidedong2000@163.com )? thanks

**Comment by HopLee6** [comment]
i try to sent you the model but your email cannot be reached.

**Comment by hiredd** [comment]
> i try to sent you the model but your email cannot be reached.

try  wcgsir@gmail.com  thanks

**Comment by hiredd** [comment]
sucessfull download the model  ,thanlks
