### ISSUE TITLE
Why final output is clamped between (0,1)?

### ISSUE THREAD

**Issue by vineel96** [HopLee6/RRIN#7]
@HopLee6  hi,
In model.py file at line 55, why final output is restricted between 0 and 1? Is there any specific reason? or specific to data range?

Thank You.

**Comment by HopLee6** [comment]
Yes, we restrict the output to range [0,1] for correctly concerting a tensor to PIL image. 
See `torchvision.transforms.ToTensor` for details.

**Comment by vineel96** [comment]
Hi,

1. Input is tensor which is scaled between [0,1] and it is given during training the model. so the model learns only values between [0,1] only , as the input is scaled to [0,1]. so why the output from model is clamped again between [0,1] ? as model tries to give output values only between [0,1]
2. I have  float32 type raw weather radar data, so transforms.toTensor() do not apply any normalization as it assumes that if input type is float32 it will be already between [0,1] and no conversion is done. so in this case no need to clamp between [0,1] if i dont want to convert to PIL image?
3. No need to clamp between [0,1] if i dont want to convert to PIL image? instead visualize using matplotlib with numpy array? will it remain same?

Thank You

**Comment by HopLee6** [comment]
Even though the input tensor is [0,1], we still cannot guarantee the output of the model is between [0,1].
I think it's ok to drop the clamp when training, but it's better to have the clamp when inference.

**Comment by vineel96** [comment]
Thank you, i have other doubt.
Using (t-1) frame, t frame can we interpolate (t+1) frame? i.e can we do extraplolation to (t+1)th frame and further frames?
In model.py file at line 35 and line 36, can we change this optical flow estimation formula for (t+1) frame? is this possible?
I have changed as follows, is this correct?(i am might be wrong)
Flow_t_0 = -(t-1)*(t+1)*Flow_0_1  +  (t+1)*(t+1)*Flow_1_0
Flow_t_1 = -(t-1)*(t+1)*Flow_0_1  +  (t-1)*(t-1)*Flow_1_0
Can you suggest any changes to it?

**Comment by Yu-Fangxu** [comment]
您好，想问问您的这个代码输入边长可以不是16的倍数吗 比如宽是180，但我直接送图片进模型他将最后一行像素往下填充了。该怎么改啊
