### ISSUE TITLE
输入的尺寸问题

### ISSUE THREAD

**Issue by Yu-Fangxu** [HopLee6/RRIN#8]
您好，想问问您的这个代码输入边长可以不是16的倍数吗 比如宽是180，但我直接送图片进模型他将最后一行像素往下填充了。该怎么改啊

**Comment by HopLee6** [comment]
demo.py可以接受边长不是16倍数的图片。对于这样的图片会自动进行填充，插值完之后会对填充的部分进行裁剪。

**Comment by Yu-Fangxu** [comment]
是的，但是这样的话生成的图片底部会有缺陷，与上面生成的部分差异很大

**Comment by HopLee6** [comment]
可以不用padding，用resize将图片边长变成16的倍数，插值完之后再resize回去
